# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb6f8d3c17b94863373e72415594976bba8baafbabc13e55e491ca24a762b4a7f7382b396535ed9a6c70eb5b5f94065d99962cfada36993abe42b781fb994e68

test:
  secret_key_base: d7decc5b700ccd72179f32da944d378a312793675976de64f040020c33beb6f3ccc9512cdf61274f8bb17b40ea8e2cb67ad7899b5d757d475763c2fa9fd333a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
